In [ ]:
import pandas as pd 
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv('train_data.txt', sep=':::', engine='python', header=None)

In [3]:
# df = pd.read_csv(df, sep=r'\s*%:::\s*%', engine='python', header=None)
print(df)

           0                                             1              2  \
0          1                 Oscar et la dame rose (2009)          drama
1          2                                 Cupid (1997)       thriller
2          3             Young, Wild and Wonderful (1980)          adult
3          4                        The Secret Sin (1915)          drama
4          5                       The Unrecovered (2007)          drama
...      ...                                           ...            ...
54209  54210                              "Bonino" (1953)         comedy
54210  54211                  Dead Girls Don't Cry (????)         horror
54211  54212    Ronald Goedemondt: Ze bestaan echt (2008)    documentary
54212  54213                     Make Your Own Bed (1944)         comedy
54213  54214   Nature's Fury: Storm of the Century (2006)        history

                                                       3
0       Listening in to a conversation between his do...
1       A brother and sister with a past incestuous r...
2       As the bus empties the students for their fie...
3       To help their unemployed father make ends mee...
4       The film's title refers not only to the un-re...
...                                                  ...
54209   This short-lived NBC live sitcom centered on ...
54210   The NEXT Generation of EXPLOITATION. The sist...
54211   Ze bestaan echt, is a stand-up comedy about g...
54212   Walter and Vivian live in the country and hav...
54213   On Labor Day Weekend, 1935, the most intense ...

[54214 rows x 4 columns]

In [4]:
df.columns = ['id', 'name', 'genre', 'description']

In [10]:
df

,id,name,genre,description,year
0,1,Oscar et la dame rose (2009),drama,Listening in to a conversation between his do...,2009
1,2,Cupid (1997),thriller,A brother and sister with a past incestuous r...,1997
2,3,"Young, Wild and Wonderful (1980)",adult,As the bus empties the students for their fie...,1980
3,4,The Secret Sin (1915),drama,To help their unemployed father make ends mee...,1915
4,5,The Unrecovered (2007),drama,The film's title refers not only to the un-re...,2007
...,...,...,...,...,...
54209,54210,"""Bonino"" (1953)",comedy,This short-lived NBC live sitcom centered on ...,1953
54210,54211,Dead Girls Don't Cry (????),horror,The NEXT Generation of EXPLOITATION. The sist...,NaN
54211,54212,Ronald Goedemondt: Ze bestaan echt (2008),documentary,"Ze bestaan echt, is a stand-up comedy about g...",2008
54212,54213,Make Your Own Bed (1944),comedy,Walter and Vivian live in the country and hav...,1944
54213,54214,Nature's Fury: Storm of the Century (2006),history,"On Labor Day Weekend, 1935, the most intense ...",2006

In [7]:
df['year'] = df['name'].str.extract(r'\((\d{4})\)')

In [16]:
df.sample(2)

,id,name,genre,description,year
30923,30924,Amoklauf (1994),horror,"Excerpts of the life of a waiter who, living ...",1994
30637,30638,Gong fu xiao zi (1977),action,"He's lost his memory, but not his skill: Afte...",1977

In [ ]:
## This line removes given year and also removes this "(????)" 

df['name'] = df['name'].str.replace(r'\s*\((\d{4}|\?{4})\)', '', regex=True)

In [25]:

df['year'] = pd.to_datetime(df['year'], format='%Y')

In [26]:
df.sample(2)

,id,name,genre,description,year
52067,52068,Meeting at the Building,short,It's a summer morning at the Building 111 of ...,2012-01-01
9860,9861,Zulu Meets Jazz,documentary,ZULU meets JAZZ provides an opportunity to le...,2008-01-01

(49867, 5)